// <auto-generated> - Template:MvvmLightModelObject, Version:1.1, Id:c644a31c-7ebc-4383-bc7f-0ea7c5bf6ed4
using GalaSoft.MvvmLight;

namespace MSC.CM.Xam.ModelObj.CM
{
	public partial class BlobFileType : ObservableObject
	{
		public BlobFileType()
		{
			BlobFiles = new System.Collections.Generic.List<BlobFile>(); // Reverse Navigation
			BlobFileTypes = new System.Collections.Generic.List<BlobFileType>(); // Reverse Navigation

			InitializePartial();
		}

		private int _blobFileTypeId;
		private string _categoryType;
		private string _createdBy;
		private System.DateTime _createdUtcDate;
		private int _dataVersion;
		private string _generalType;
		private bool _isDeleted;
		private string _modifiedBy;
		private System.DateTime _modifiedUtcDate;
		private string _name;
		private int? _resizeFromBlobFileTypeId;
		private int? _resolutionX;
		private int? _resolutionY;


		public int BlobFileTypeId
		{
			get { return _blobFileTypeId; }
			set
			{
				Set<int>(() => BlobFileTypeId, ref _blobFileTypeId, value);
				RunCustomLogicSetBlobFileTypeId(value);
			}
		}

		public string CategoryType
		{
			get { return _categoryType; }
			set
			{
				Set<string>(() => CategoryType, ref _categoryType, value);
				RunCustomLogicSetCategoryType(value);
			}
		}

		public string CreatedBy
		{
			get { return _createdBy; }
			set
			{
				Set<string>(() => CreatedBy, ref _createdBy, value);
				RunCustomLogicSetCreatedBy(value);
			}
		}

		public System.DateTime CreatedUtcDate
		{
			get { return _createdUtcDate; }
			set
			{
				Set<System.DateTime>(() => CreatedUtcDate, ref _createdUtcDate, value);
				RunCustomLogicSetCreatedUtcDate(value);
			}
		}

		public int DataVersion
		{
			get { return _dataVersion; }
			set
			{
				Set<int>(() => DataVersion, ref _dataVersion, value);
				RunCustomLogicSetDataVersion(value);
			}
		}

		public string GeneralType
		{
			get { return _generalType; }
			set
			{
				Set<string>(() => GeneralType, ref _generalType, value);
				RunCustomLogicSetGeneralType(value);
			}
		}

		public bool IsDeleted
		{
			get { return _isDeleted; }
			set
			{
				Set<bool>(() => IsDeleted, ref _isDeleted, value);
				RunCustomLogicSetIsDeleted(value);
			}
		}

		public string ModifiedBy
		{
			get { return _modifiedBy; }
			set
			{
				Set<string>(() => ModifiedBy, ref _modifiedBy, value);
				RunCustomLogicSetModifiedBy(value);
			}
		}

		public System.DateTime ModifiedUtcDate
		{
			get { return _modifiedUtcDate; }
			set
			{
				Set<System.DateTime>(() => ModifiedUtcDate, ref _modifiedUtcDate, value);
				RunCustomLogicSetModifiedUtcDate(value);
			}
		}

		public string Name
		{
			get { return _name; }
			set
			{
				Set<string>(() => Name, ref _name, value);
				RunCustomLogicSetName(value);
			}
		}

		public int? ResizeFromBlobFileTypeId
		{
			get { return _resizeFromBlobFileTypeId; }
			set
			{
				Set<int?>(() => ResizeFromBlobFileTypeId, ref _resizeFromBlobFileTypeId, value);
				RunCustomLogicSetResizeFromBlobFileTypeId(value);
			}
		}

		public int? ResolutionX
		{
			get { return _resolutionX; }
			set
			{
				Set<int?>(() => ResolutionX, ref _resolutionX, value);
				RunCustomLogicSetResolutionX(value);
			}
		}

		public int? ResolutionY
		{
			get { return _resolutionY; }
			set
			{
				Set<int?>(() => ResolutionY, ref _resolutionY, value);
				RunCustomLogicSetResolutionY(value);
			}
		}

		public virtual System.Collections.Generic.IList<BlobFile> BlobFiles { get; set; } // Many to many mapping
		public virtual System.Collections.Generic.IList<BlobFileType> BlobFileTypes { get; set; } // Many to many mapping
		public virtual BlobFileType ResizeFromBlobFileType { get; set; } 


		partial void InitializePartial();

		#region RunCustomLogicSet

		partial void RunCustomLogicSetBlobFileTypeId(int value);
		partial void RunCustomLogicSetCategoryType(string value);
		partial void RunCustomLogicSetCreatedBy(string value);
		partial void RunCustomLogicSetCreatedUtcDate(System.DateTime value);
		partial void RunCustomLogicSetDataVersion(int value);
		partial void RunCustomLogicSetGeneralType(string value);
		partial void RunCustomLogicSetIsDeleted(bool value);
		partial void RunCustomLogicSetModifiedBy(string value);
		partial void RunCustomLogicSetModifiedUtcDate(System.DateTime value);
		partial void RunCustomLogicSetName(string value);
		partial void RunCustomLogicSetResizeFromBlobFileTypeId(int? value);
		partial void RunCustomLogicSetResolutionX(int? value);
		partial void RunCustomLogicSetResolutionY(int? value);

		#endregion RunCustomLogicSet

	}
}
