// <auto-generated> - Template:MvvmLightModelObject, Version:1.1, Id:c644a31c-7ebc-4383-bc7f-0ea7c5bf6ed4
using GalaSoft.MvvmLight;

namespace MSC.CM.Xam.ModelObj.CM
{
	public partial class LogType : ObservableObject
	{
		public LogType()
		{
			InitializePartial();
		}

		private int _id;
		private string _type;


		public int Id
		{
			get { return _id; }
			set
			{
				Set<int>(() => Id, ref _id, value);
				RunCustomLogicSetId(value);
			}
		}

		public string Type
		{
			get { return _type; }
			set
			{
				Set<string>(() => Type, ref _type, value);
				RunCustomLogicSetType(value);
			}
		}



		partial void InitializePartial();

		#region RunCustomLogicSet

		partial void RunCustomLogicSetId(int value);
		partial void RunCustomLogicSetType(string value);

		#endregion RunCustomLogicSet

	}
}
