// <auto-generated> - Template:SqliteModelData, Version:1.1, Id:c5caad15-b3be-4443-87d8-7cabde59f7b0
using SQLite;

namespace MSC.CM.Xam.ModelData.CM
{
	[Table("BlobFile")]
	public partial class BlobFile
	{

		[PrimaryKey]
		public System.Guid BlobFileId { get; set; }

		public int? BlobFileTypeId { get; set; }
		public string BlobUri { get; set; }
		public byte[] Content { get; set; }
		public string CreatedBy { get; set; }
		public System.DateTime CreatedUtcDate { get; set; }
		public int DataVersion { get; set; }
		public string DiscreteMimeType { get; set; }
		public bool IsDeleted { get; set; }
		public string ModifiedBy { get; set; }
		public System.DateTime ModifiedUtcDate { get; set; }
		public string Name { get; set; }
		public System.Guid? ParentBlobFileId { get; set; }
		public bool? RequiresResize { get; set; }
		public bool? ResizeComplete { get; set; }
		public long? SizeInBytes { get; set; }
	}
}
