// <auto-generated> - Template:SqliteModelData, Version:1.1, Id:c5caad15-b3be-4443-87d8-7cabde59f7b0
using SQLite;

namespace MSC.CM.Xam.ModelData.CM
{
	[Table("GenderType")]
	public partial class GenderType
	{
		public string Code { get; set; }
		public string CreatedBy { get; set; }
		public System.DateTime CreatedUtcDate { get; set; }
		public int DataVersion { get; set; }

		[PrimaryKey]
		public int GenderTypeId { get; set; }

		public bool IsDeleted { get; set; }
		public string ModifiedBy { get; set; }
		public System.DateTime ModifiedUtcDate { get; set; }
	}
}
