// <auto-generated> - Template:SqliteModelData, Version:1.1, Id:c5caad15-b3be-4443-87d8-7cabde59f7b0
using SQLite;

namespace MSC.CM.Xam.ModelData.CM
{
	[Table("Log")]
	public partial class Log
	{
		public string ClientIpAddress { get; set; }
		public System.DateTime Date { get; set; }
		public string Exception { get; set; }
		public long? ExecutionTimeInMilliseconds { get; set; }
		public string HttpResponseStatusCode { get; set; }

		[PrimaryKey]
		public int Id { get; set; }

		public string Level { get; set; }
		public string Logger { get; set; }
		public System.Guid? LogGuid { get; set; }
		public int? LogMessageTypeId { get; set; }
		public string Message { get; set; }
		public string MethodName { get; set; }
		public string Thread { get; set; }
		public string Url { get; set; }
		public string UserName { get; set; }
	}
}
