// <auto-generated> - Template:SqliteModelData, Version:1.1, Id:c5caad15-b3be-4443-87d8-7cabde59f7b0
using SQLite;

namespace MSC.CM.Xam.ModelData.CM
{
	[Table("LookupList")]
	public partial class LookupList
	{
		public string CreatedBy { get; set; }
		public System.DateTime CreatedUtcDate { get; set; }
		public string CustomJson { get; set; }
		public int DataVersion { get; set; }
		public string Description { get; set; }
		public int DisplayPriority { get; set; }
		public string DisplayText { get; set; }
		public string ForeignKeyTableName { get; set; }
		public int ForeignKeyTablePkId { get; set; }
		public bool IsDeleted { get; set; }
		public int LanguageTypeId { get; set; }

		[PrimaryKey]
		public int LookupListId { get; set; }

		public string ModifiedBy { get; set; }
		public System.DateTime ModifiedUtcDate { get; set; }
	}
}
