// <auto-generated> - Template:SqliteModelData, Version:1.1, Id:c5caad15-b3be-4443-87d8-7cabde59f7b0
using SQLite;

namespace MSC.CM.Xam.ModelData.CM
{
	[Table("Session")]
	public partial class Session
	{
		public string CreatedBy { get; set; }
		public System.DateTime CreatedUtcDate { get; set; }
		public int DataVersion { get; set; }
		public string Description { get; set; }
		public System.DateTime? EndTime { get; set; }
		public bool IsDeleted { get; set; }
		public string ModifiedBy { get; set; }
		public System.DateTime ModifiedUtcDate { get; set; }
		public int? RoomId { get; set; }

		[PrimaryKey]
		public int SessionId { get; set; }

		public string ShortTitle { get; set; }
		public System.DateTime? StartTime { get; set; }
		public string Title { get; set; }
	}
}
