// <auto-generated> - Template:SqliteModelData, Version:1.1, Id:c5caad15-b3be-4443-87d8-7cabde59f7b0
using SQLite;

namespace MSC.CM.Xam.ModelData.CM
{
	[Table("SessionLike")]
	public partial class SessionLike
	{
		public string CreatedBy { get; set; }
		public System.DateTime CreatedUtcDate { get; set; }
		public int DataVersion { get; set; }
		public bool IsDeleted { get; set; }
		public string ModifiedBy { get; set; }
		public System.DateTime ModifiedUtcDate { get; set; }

		// Mutiple primary keys - composite PK used instead [Indexed(Name = "SessionLike", Order = 1, Unique = true)]
		public int SessionId { get; set; }


		// Mutiple primary keys - composite PK used instead [Indexed(Name = "SessionLike", Order = 2, Unique = true)]
		public int UserProfileId { get; set; }

		[PrimaryKey]
		public string SessionIdUserProfileId { get; set; }
	}
}
