// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MSC.ConferenceMate.Repository.Entities.CM
{

    // BlobFile
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class BlobFile
    {
        public System.Guid BlobFileId { get; set; } // BlobFileId (Primary key)
        public string Name { get; set; } // Name (length: 255)
        public string DiscreteMimeType { get; set; } // DiscreteMimeType (length: 100)
        public byte[] Content { get; set; } // Content
        public string BlobUri { get; set; } // BlobUri (length: 2000)
        public long? SizeInBytes { get; set; } // SizeInBytes
        public System.Guid? ParentBlobFileId { get; set; } // ParentBlobFileId
        public int? BlobFileTypeId { get; set; } // BlobFileTypeId
        public bool? RequiresResize { get; set; } // RequiresResize
        public bool? ResizeComplete { get; set; } // ResizeComplete
        public int DataVersion { get; set; } // DataVersion
        public System.DateTime CreatedUtcDate { get; set; } // CreatedUtcDate
        public string CreatedBy { get; set; } // CreatedBy (length: 200)
        public System.DateTime ModifiedUtcDate { get; set; } // ModifiedUtcDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 200)
        public bool IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child UserProfiles where [UserProfile].[PhotoBlobFileId] point to this entity (FK_UserProfile_BlobFile)
        /// </summary>
        public System.Collections.Generic.ICollection<UserProfile> UserProfiles { get; set; } // UserProfile.FK_UserProfile_BlobFile

        // Foreign keys

        /// <summary>
        /// Parent BlobFileType pointed by [BlobFile].([BlobFileTypeId]) (FK_BlobFileType)
        /// </summary>
        public BlobFileType BlobFileType { get; set; } // FK_BlobFileType

        public BlobFile()
        {
            DataVersion = 1;
            CreatedUtcDate = System.DateTime.UtcNow;
            ModifiedUtcDate = System.DateTime.UtcNow;
            IsDeleted = false;
            UserProfiles = new System.Collections.Generic.List<UserProfile>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
