// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MSC.ConferenceMate.Repository.Entities.CM
{

    // FeaturedEvent
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class FeaturedEvent
    {
        public int FeaturedEventId { get; set; } // FeaturedEventId (Primary key)
        public string Title { get; set; } // Title (length: 1000)
        public string ShortTitle { get; set; } // ShortTitle (length: 500)
        public string Description { get; set; } // Description (length: 4000)
        public string Location { get; set; } // Location (length: 1000)
        public System.DateTime? StartTime { get; set; } // StartTime
        public System.DateTime? EndTime { get; set; } // EndTime
        public bool IsAllDay { get; set; } // IsAllDay
        public int DataVersion { get; set; } // DataVersion
        public System.DateTime CreatedUtcDate { get; set; } // CreatedUtcDate
        public string CreatedBy { get; set; } // CreatedBy (length: 200)
        public System.DateTime ModifiedUtcDate { get; set; } // ModifiedUtcDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 200)
        public bool IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child Feedbacks where [Feedback].[FeaturedEventId] point to this entity (FK_Feedback_FeaturedEvent)
        /// </summary>
        public System.Collections.Generic.ICollection<Feedback> Feedbacks { get; set; } // Feedback.FK_Feedback_FeaturedEvent
        /// <summary>
        /// Child SponsorFeaturedEvents where [Sponsor_FeaturedEvent].[FeaturedEventId] point to this entity (FK_Sponsor_FeaturedEvent_FeaturedEvent)
        /// </summary>
        public System.Collections.Generic.ICollection<SponsorFeaturedEvent> SponsorFeaturedEvents { get; set; } // Sponsor_FeaturedEvent.FK_Sponsor_FeaturedEvent_FeaturedEvent

        public FeaturedEvent()
        {
            IsAllDay = false;
            DataVersion = 1;
            CreatedUtcDate = System.DateTime.UtcNow;
            ModifiedUtcDate = System.DateTime.UtcNow;
            IsDeleted = false;
            Feedbacks = new System.Collections.Generic.List<Feedback>();
            SponsorFeaturedEvents = new System.Collections.Generic.List<SponsorFeaturedEvent>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
