// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MSC.ConferenceMate.Repository.Entities.CM
{

    // LookupList
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class LookupList
    {
        public int LookupListId { get; set; } // LookupListId (Primary key)
        public int LanguageTypeId { get; set; } // LanguageTypeId
        public int ForeignKeyTablePkId { get; set; } // ForeignKeyTablePkId
        public string ForeignKeyTableName { get; set; } // ForeignKeyTableName (length: 200)
        public int DisplayPriority { get; set; } // DisplayPriority
        public string DisplayText { get; set; } // DisplayText (length: 4000)
        public string Description { get; set; } // Description (length: 2000)
        public string CustomJson { get; set; } // CustomJson
        public int DataVersion { get; set; } // DataVersion
        public System.DateTime CreatedUtcDate { get; set; } // CreatedUtcDate
        public string CreatedBy { get; set; } // CreatedBy (length: 200)
        public System.DateTime ModifiedUtcDate { get; set; } // ModifiedUtcDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 200)
        public bool IsDeleted { get; set; } // IsDeleted

        // Foreign keys

        /// <summary>
        /// Parent LanguageType pointed by [LookupList].([LanguageTypeId]) (FK_LookupList_LanguageType)
        /// </summary>
        public LanguageType LanguageType { get; set; } // FK_LookupList_LanguageType

        public LookupList()
        {
            DataVersion = 1;
            CreatedUtcDate = System.DateTime.UtcNow;
            ModifiedUtcDate = System.DateTime.UtcNow;
            IsDeleted = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
