// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MSC.ConferenceMate.Repository.Entities.CM
{

    // RefreshToken
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class RefreshToken
    {
        public int RefreshTokenId { get; set; } // RefreshTokenId (Primary key)
        public string AspNetUsersId { get; set; } // AspNetUsersId (length: 128)
        public string Token { get; set; } // Token
        public System.DateTime IssuedUtc { get; set; } // IssuedUtc
        public System.DateTime ExpiresUtc { get; set; } // ExpiresUtc
        public string ProtectedTicket { get; set; } // ProtectedTicket

        // Foreign keys

        /// <summary>
        /// Parent AspNetUser pointed by [RefreshToken].([AspNetUsersId]) (FK_RefreshToken_AspNetUsers_AspNetUsersId)
        /// </summary>
        public AspNetUser AspNetUser { get; set; } // FK_RefreshToken_AspNetUsers_AspNetUsersId

        public RefreshToken()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
