// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MSC.ConferenceMate.Repository.Entities.CM
{

    // Sponsor
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Sponsor
    {
        public int SponsorId { get; set; } // SponsorId (Primary key)
        public int SponsorTypeId { get; set; } // SponsorTypeId
        public string Title { get; set; } // Title (length: 1000)
        public string ShortTitle { get; set; } // ShortTitle (length: 500)
        public string Description { get; set; } // Description (length: 4000)
        public string ImageUrl { get; set; } // ImageUrl (length: 1000)
        public string WebsiteUrl { get; set; } // WebsiteUrl (length: 1000)
        public string TwitterUrl { get; set; } // TwitterUrl (length: 1000)
        public string BoothLocation { get; set; } // BoothLocation (length: 1000)
        public int Rank { get; set; } // Rank
        public int DataVersion { get; set; } // DataVersion
        public System.DateTime CreatedUtcDate { get; set; } // CreatedUtcDate
        public string CreatedBy { get; set; } // CreatedBy (length: 200)
        public System.DateTime ModifiedUtcDate { get; set; } // ModifiedUtcDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 200)
        public bool IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child SponsorFeaturedEvents where [Sponsor_FeaturedEvent].[SponsorId] point to this entity (FK_Sponsor_FeaturedEvent_Sponsor)
        /// </summary>
        public System.Collections.Generic.ICollection<SponsorFeaturedEvent> SponsorFeaturedEvents { get; set; } // Sponsor_FeaturedEvent.FK_Sponsor_FeaturedEvent_Sponsor

        // Foreign keys

        /// <summary>
        /// Parent SponsorType pointed by [Sponsor].([SponsorTypeId]) (FK_Sponsor_SponsorType)
        /// </summary>
        public SponsorType SponsorType { get; set; } // FK_Sponsor_SponsorType

        public Sponsor()
        {
            Rank = 100;
            DataVersion = 1;
            CreatedUtcDate = System.DateTime.UtcNow;
            ModifiedUtcDate = System.DateTime.UtcNow;
            IsDeleted = false;
            SponsorFeaturedEvents = new System.Collections.Generic.List<SponsorFeaturedEvent>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
