// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MSC.ConferenceMate.Repository.Entities.CM
{

    // Sponsor_FeaturedEvent
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class SponsorFeaturedEventConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SponsorFeaturedEvent>
    {
        public SponsorFeaturedEventConfiguration()
            : this("dbo")
        {
        }

        public SponsorFeaturedEventConfiguration(string schema)
        {
            ToTable("Sponsor_FeaturedEvent", schema);
            HasKey(x => new { x.SponsorId, x.FeaturedEventId });

            Property(x => x.SponsorId).HasColumnName(@"SponsorId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.FeaturedEventId).HasColumnName(@"FeaturedEventId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.DataVersion).HasColumnName(@"DataVersion").HasColumnType("int").IsRequired();
            Property(x => x.CreatedUtcDate).HasColumnName(@"CreatedUtcDate").HasColumnType("datetime2").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar").IsRequired().HasMaxLength(200);
            Property(x => x.ModifiedUtcDate).HasColumnName(@"ModifiedUtcDate").HasColumnType("datetime2").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("nvarchar").IsRequired().HasMaxLength(200);
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasRequired(a => a.FeaturedEvent).WithMany(b => b.SponsorFeaturedEvents).HasForeignKey(c => c.FeaturedEventId).WillCascadeOnDelete(false); // FK_Sponsor_FeaturedEvent_FeaturedEvent
            HasRequired(a => a.Sponsor).WithMany(b => b.SponsorFeaturedEvents).HasForeignKey(c => c.SponsorId).WillCascadeOnDelete(false); // FK_Sponsor_FeaturedEvent_Sponsor
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
