// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MSC.ConferenceMate.Repository.Entities.CM
{

    // Sponsor_FeaturedEvent
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class SponsorFeaturedEvent
    {
        public int SponsorId { get; set; } // SponsorId (Primary key)
        public int FeaturedEventId { get; set; } // FeaturedEventId (Primary key)
        public int DataVersion { get; set; } // DataVersion
        public System.DateTime CreatedUtcDate { get; set; } // CreatedUtcDate
        public string CreatedBy { get; set; } // CreatedBy (length: 200)
        public System.DateTime ModifiedUtcDate { get; set; } // ModifiedUtcDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 200)
        public bool IsDeleted { get; set; } // IsDeleted

        // Foreign keys

        /// <summary>
        /// Parent FeaturedEvent pointed by [Sponsor_FeaturedEvent].([FeaturedEventId]) (FK_Sponsor_FeaturedEvent_FeaturedEvent)
        /// </summary>
        public FeaturedEvent FeaturedEvent { get; set; } // FK_Sponsor_FeaturedEvent_FeaturedEvent

        /// <summary>
        /// Parent Sponsor pointed by [Sponsor_FeaturedEvent].([SponsorId]) (FK_Sponsor_FeaturedEvent_Sponsor)
        /// </summary>
        public Sponsor Sponsor { get; set; } // FK_Sponsor_FeaturedEvent_Sponsor

        public SponsorFeaturedEvent()
        {
            DataVersion = 1;
            CreatedUtcDate = System.DateTime.UtcNow;
            ModifiedUtcDate = System.DateTime.UtcNow;
            IsDeleted = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
