// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MSC.ConferenceMate.Repository.Entities.CM
{

    // Sponsor
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class SponsorConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Sponsor>
    {
        public SponsorConfiguration()
            : this("dbo")
        {
        }

        public SponsorConfiguration(string schema)
        {
            ToTable("Sponsor", schema);
            HasKey(x => x.SponsorId);

            Property(x => x.SponsorId).HasColumnName(@"SponsorId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SponsorTypeId).HasColumnName(@"SponsorTypeId").HasColumnType("int").IsRequired();
            Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar").IsRequired().HasMaxLength(1000);
            Property(x => x.ShortTitle).HasColumnName(@"ShortTitle").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsOptional().HasMaxLength(4000);
            Property(x => x.ImageUrl).HasColumnName(@"ImageUrl").HasColumnType("nvarchar").IsOptional().HasMaxLength(1000);
            Property(x => x.WebsiteUrl).HasColumnName(@"WebsiteUrl").HasColumnType("nvarchar").IsOptional().HasMaxLength(1000);
            Property(x => x.TwitterUrl).HasColumnName(@"TwitterUrl").HasColumnType("nvarchar").IsOptional().HasMaxLength(1000);
            Property(x => x.BoothLocation).HasColumnName(@"BoothLocation").HasColumnType("nvarchar").IsOptional().HasMaxLength(1000);
            Property(x => x.Rank).HasColumnName(@"Rank").HasColumnType("int").IsRequired();
            Property(x => x.DataVersion).HasColumnName(@"DataVersion").HasColumnType("int").IsRequired();
            Property(x => x.CreatedUtcDate).HasColumnName(@"CreatedUtcDate").HasColumnType("datetime2").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar").IsRequired().HasMaxLength(200);
            Property(x => x.ModifiedUtcDate).HasColumnName(@"ModifiedUtcDate").HasColumnType("datetime2").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("nvarchar").IsRequired().HasMaxLength(200);
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasRequired(a => a.SponsorType).WithMany(b => b.Sponsors).HasForeignKey(c => c.SponsorTypeId).WillCascadeOnDelete(false); // FK_Sponsor_SponsorType
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
