// <auto-generated> - Template:DTO, Version:1.1, Id:58fa7ee2-89f7-41e6-85ed-8d4482653990
namespace MSC.ConferenceMate.DTO.CM
{
	public partial class BlobFileType
	{
		public BlobFileType()
		{
			InitializePartial();
		}

		public int BlobFileTypeId { get; set; } // Primary key
		public string Name { get; set; }
		public string GeneralType { get; set; }
		public string CategoryType { get; set; }
		public int? ResolutionX { get; set; }
		public int? ResolutionY { get; set; }
		public int? ResizeFromBlobFileTypeId { get; set; }
		public int DataVersion { get; set; }
		public System.DateTime CreatedUtcDate { get; set; }
		public string CreatedBy { get; set; }
		public System.DateTime ModifiedUtcDate { get; set; }
		public string ModifiedBy { get; set; }
		public bool IsDeleted { get; set; }
		// public virtual System.Collections.Generic.ICollection<BlobFile> BlobFiles { get; set; } // Many to many mapping -- Excluded navigation property per configuration.
		// public virtual System.Collections.Generic.ICollection<BlobFileType> BlobFileTypes { get; set; } // Many to many mapping -- Excluded navigation property per configuration.
		// public virtual BlobFileType ResizeFromBlobFileType { get; set; }  -- Excluded navigation property per configuration.


		partial void InitializePartial();

	}
}
