// <auto-generated> - Template:DTO, Version:1.1, Id:58fa7ee2-89f7-41e6-85ed-8d4482653990
namespace MSC.ConferenceMate.DTO.CM
{
	public partial class LogType
	{
		public LogType()
		{
			InitializePartial();
		}

		public int Id { get; set; } // Primary key
		public string Type { get; set; }


		partial void InitializePartial();

	}
}
