// <auto-generated> - Template:DTO, Version:1.1, Id:58fa7ee2-89f7-41e6-85ed-8d4482653990
namespace MSC.ConferenceMate.DTO.CM
{
	public partial class LookupList
	{
		public LookupList()
		{
			InitializePartial();
		}

		public int LookupListId { get; set; } // Primary key
		public int LanguageTypeId { get; set; }
		public int ForeignKeyTablePkId { get; set; }
		public string ForeignKeyTableName { get; set; }
		public int DisplayPriority { get; set; }
		public string DisplayText { get; set; }
		public string Description { get; set; }
		public string CustomJson { get; set; }
		public int DataVersion { get; set; }
		public System.DateTime CreatedUtcDate { get; set; }
		public string CreatedBy { get; set; }
		public System.DateTime ModifiedUtcDate { get; set; }
		public string ModifiedBy { get; set; }
		public bool IsDeleted { get; set; }
		public virtual LanguageType LanguageType { get; set; } 


		partial void InitializePartial();

	}
}
