// <auto-generated> - Template:DTO, Version:1.1, Id:58fa7ee2-89f7-41e6-85ed-8d4482653990
namespace MSC.ConferenceMate.DTO.CM
{
	public partial class Sponsor
	{
		public Sponsor()
		{
			InitializePartial();
		}

		public int SponsorId { get; set; } // Primary key
		public int SponsorTypeId { get; set; }
		public string Title { get; set; }
		public string ShortTitle { get; set; }
		public string Description { get; set; }
		public string ImageUrl { get; set; }
		public string WebsiteUrl { get; set; }
		public string TwitterUrl { get; set; }
		public string BoothLocation { get; set; }
		public int Rank { get; set; }
		public int DataVersion { get; set; }
		public System.DateTime CreatedUtcDate { get; set; }
		public string CreatedBy { get; set; }
		public System.DateTime ModifiedUtcDate { get; set; }
		public string ModifiedBy { get; set; }
		public bool IsDeleted { get; set; }
		public virtual System.Collections.Generic.ICollection<SponsorFeaturedEvent> SponsorFeaturedEvents { get; set; } // Many to many mapping
		public virtual SponsorType SponsorType { get; set; } 


		partial void InitializePartial();

	}
}
