// <auto-generated> - Template:AutoMapperProfile, Version:1.1, Id:f3f865a7-e545-4bc4-b0ba-c9e7ee587e73
using AutoMapper;
using xDTO = MSC.ConferenceMate.DTO.CM;
using xENT = MSC.ConferenceMate.Repository.Entities.CM;

namespace MSC.ConferenceMate.Repository.Infrastructure
{
	public partial class CMAutoMapperProfile : Profile
	{
		public CMAutoMapperProfile()
		{
			InitializeProfile();
			InitializePartial();
		}

		partial void InitializePartial();

		private void InitializeProfile()
		{
			CreateMap<xDTO.Announcement, xENT.Announcement>()
			.ReverseMap();

			CreateMap<xDTO.BlobFile, xENT.BlobFile>()
				.ForMember(d => d.UserProfiles, opt => opt.Ignore()) // Reverse nav -- Excluded navigation property per configuration.
				// .ForMember(d => d.BlobFileType, opt => opt.Ignore())
			.ReverseMap();

			CreateMap<xDTO.BlobFileType, xENT.BlobFileType>()
				.ForMember(d => d.BlobFiles, opt => opt.Ignore()) // Reverse nav -- Excluded navigation property per configuration.
				.ForMember(d => d.BlobFileTypes, opt => opt.Ignore()) // Reverse nav -- Excluded navigation property per configuration.
				.ForMember(d => d.ResizeFromBlobFileType, opt => opt.Ignore()) //  -- Excluded navigation property per configuration.
			.ReverseMap();

			CreateMap<xDTO.FeaturedEvent, xENT.FeaturedEvent>()
				// .ForMember(d => d.Feedbacks, opt => opt.Ignore()) // Reverse nav
				// .ForMember(d => d.SponsorFeaturedEvents, opt => opt.Ignore()) // Reverse nav
			.ReverseMap();

			CreateMap<xDTO.Feedback, xENT.Feedback>()
				.ForMember(d => d.FeaturedEvent, opt => opt.Ignore()) //  -- Excluded navigation property per configuration.
				// .ForMember(d => d.FeedbackInitiatorType, opt => opt.Ignore())
				// .ForMember(d => d.FeedbackType, opt => opt.Ignore())
				.ForMember(d => d.Session, opt => opt.Ignore()) //  -- Excluded navigation property per configuration.
				// .ForMember(d => d.UserProfile, opt => opt.Ignore())
			.ReverseMap();

			CreateMap<xDTO.FeedbackInitiatorType, xENT.FeedbackInitiatorType>()
				.ForMember(d => d.Feedbacks, opt => opt.Ignore()) // Reverse nav -- Excluded navigation property per configuration.
			.ReverseMap();

			CreateMap<xDTO.FeedbackType, xENT.FeedbackType>()
				.ForMember(d => d.Feedbacks, opt => opt.Ignore()) // Reverse nav -- Excluded navigation property per configuration.
			.ReverseMap();

			CreateMap<xDTO.GenderType, xENT.GenderType>()
				// .ForMember(d => d.UserProfiles, opt => opt.Ignore()) // Reverse nav
			.ReverseMap();

			CreateMap<xDTO.LanguageType, xENT.LanguageType>()
				.ForMember(d => d.LookupLists, opt => opt.Ignore()) // Reverse nav -- Excluded navigation property per configuration.
				// .ForMember(d => d.UserProfiles, opt => opt.Ignore()) // Reverse nav
			.ReverseMap();

			CreateMap<xDTO.Log, xENT.Log>()
			.ReverseMap();

			CreateMap<xDTO.LogType, xENT.LogType>()
			.ReverseMap();

			CreateMap<xDTO.LookupList, xENT.LookupList>()
				// .ForMember(d => d.LanguageType, opt => opt.Ignore())
			.ReverseMap();

			CreateMap<xDTO.Room, xENT.Room>()
				.ForMember(d => d.Sessions, opt => opt.Ignore()) // Reverse nav -- Excluded navigation property per configuration.
			.ReverseMap();

			CreateMap<xDTO.Session, xENT.Session>()
				// .ForMember(d => d.Feedbacks, opt => opt.Ignore()) // Reverse nav
				// .ForMember(d => d.SessionLikes, opt => opt.Ignore()) // Reverse nav
				// .ForMember(d => d.SessionSessionCategoryTypes, opt => opt.Ignore()) // Reverse nav
				// .ForMember(d => d.SessionSpeakers, opt => opt.Ignore()) // Reverse nav
				// .ForMember(d => d.Room, opt => opt.Ignore())
			.ReverseMap();

			CreateMap<xDTO.SessionCategoryType, xENT.SessionCategoryType>()
				// .ForMember(d => d.SessionSessionCategoryTypes, opt => opt.Ignore()) // Reverse nav
			.ReverseMap();

			CreateMap<xDTO.SessionLike, xENT.SessionLike>()
				.ForMember(d => d.Session, opt => opt.Ignore()) //  -- Excluded navigation property per configuration.
				// .ForMember(d => d.UserProfile, opt => opt.Ignore())
			.ReverseMap();

			CreateMap<xDTO.SessionSessionCategoryType, xENT.SessionSessionCategoryType>()
				.ForMember(d => d.Session, opt => opt.Ignore()) //  -- Excluded navigation property per configuration.
				.ForMember(d => d.SessionCategoryType, opt => opt.Ignore()) //  -- Excluded navigation property per configuration.
			.ReverseMap();

			CreateMap<xDTO.SessionSpeaker, xENT.SessionSpeaker>()
				.ForMember(d => d.Session, opt => opt.Ignore()) //  -- Excluded navigation property per configuration.
				// .ForMember(d => d.UserProfile, opt => opt.Ignore())
			.ReverseMap();

			CreateMap<xDTO.Sponsor, xENT.Sponsor>()
				// .ForMember(d => d.SponsorFeaturedEvents, opt => opt.Ignore()) // Reverse nav
				// .ForMember(d => d.SponsorType, opt => opt.Ignore())
			.ReverseMap();

			CreateMap<xDTO.SponsorFeaturedEvent, xENT.SponsorFeaturedEvent>()
				.ForMember(d => d.FeaturedEvent, opt => opt.Ignore()) //  -- Excluded navigation property per configuration.
				.ForMember(d => d.Sponsor, opt => opt.Ignore()) //  -- Excluded navigation property per configuration.
			.ReverseMap();

			CreateMap<xDTO.SponsorType, xENT.SponsorType>()
				.ForMember(d => d.Sponsors, opt => opt.Ignore()) // Reverse nav -- Excluded navigation property per configuration.
			.ReverseMap();

			CreateMap<xDTO.UserProfile, xENT.UserProfile>()
				.ForMember(d => d.Feedbacks, opt => opt.Ignore()) // Reverse nav -- Excluded navigation property per configuration.
				.ForMember(d => d.SessionLikes, opt => opt.Ignore()) // Reverse nav -- Excluded navigation property per configuration.
				.ForMember(d => d.SessionSpeakers, opt => opt.Ignore()) // Reverse nav -- Excluded navigation property per configuration.
				.ForMember(d => d.AspNetUser, opt => opt.Ignore()) //  -- Excluded navigation property per configuration.
				// .ForMember(d => d.BlobFile, opt => opt.Ignore())
				// .ForMember(d => d.GenderType, opt => opt.Ignore())
				// .ForMember(d => d.LanguageType, opt => opt.Ignore())
			.ReverseMap();

		}
	}
}
