// <auto-generated> - Template:ModelsBackedByDto, Version:1.1, Id:f1539c0d-024f-4b1f-b346-132cdd9dd31f
using CodeGenHero.Logging;
using CodeGenHero.DataService;
using System;
using System.Collections.Generic;
using System.Linq;
using MSC.ConferenceMate.API.Client.Interface;
using MSC.ConferenceMate.Model.CM.Interface;
using xDTO = MSC.ConferenceMate.DTO.CM;

namespace MSC.ConferenceMate.Model.CM
{

	public class LoadRequestAnnouncement : EventArgs
	{
		public LoadRequestAnnouncement(string propertyNameRequestingLoad)
		{
			PropertyNameRequestingLoad = propertyNameRequestingLoad;
		}

		public string PropertyNameRequestingLoad { get; set; }
	}


	public partial class Announcement : BaseModel<IWebApiDataServiceCM>, IAnnouncement
	{
		public event EventHandler<LoadRequestAnnouncement> OnLazyLoadRequest = delegate { }; // Empty delegate. Thus we are sure that value is always != null because no one outside of the class can change it.
		private xDTO.Announcement _dto = null;

		public Announcement(ILoggingService log, IDataService<IWebApiDataServiceCM> dataService) : base(log, dataService)
		{
			_dto = new xDTO.Announcement();
			OnLazyLoadRequest += HandleLazyLoadRequest;
		}

		public Announcement(ILoggingService log, IDataService<IWebApiDataServiceCM> dataService, xDTO.Announcement dto) : this(log, dataService)
		{
			_dto = dto;
		}


		public virtual int AnnouncementId { get { return _dto.AnnouncementId; } }
		public virtual string CreatedBy { get { return _dto.CreatedBy; } }
		public virtual System.DateTime CreatedUtcDate { get { return _dto.CreatedUtcDate; } }
		public virtual int DataVersion { get { return _dto.DataVersion; } }
		public virtual string Description { get { return _dto.Description; } }
		public virtual System.DateTime? EndTime { get { return _dto.EndTime; } }
		public virtual bool IsDeleted { get { return _dto.IsDeleted; } }
		public virtual string ModifiedBy { get { return _dto.ModifiedBy; } }
		public virtual System.DateTime ModifiedUtcDate { get { return _dto.ModifiedUtcDate; } }
		public virtual string ShortTitle { get { return _dto.ShortTitle; } }
		public virtual System.DateTime? StartTime { get { return _dto.StartTime; } }
		public virtual string Title { get { return _dto.Title; } }





	}
}
