// <auto-generated> - Template:ModelsBackedByDto, Version:1.1, Id:f1539c0d-024f-4b1f-b346-132cdd9dd31f
using CodeGenHero.Logging;
using CodeGenHero.DataService;
using System;
using System.Collections.Generic;
using System.Linq;
using MSC.ConferenceMate.API.Client.Interface;
using MSC.ConferenceMate.Model.CM.Interface;
using xDTO = MSC.ConferenceMate.DTO.CM;

namespace MSC.ConferenceMate.Model.CM
{

	public class LoadRequestBlobFileType : EventArgs
	{
		public LoadRequestBlobFileType(string propertyNameRequestingLoad)
		{
			PropertyNameRequestingLoad = propertyNameRequestingLoad;
		}

		public string PropertyNameRequestingLoad { get; set; }
	}


	public partial class BlobFileType : BaseModel<IWebApiDataServiceCM>, IBlobFileType
	{
		public event EventHandler<LoadRequestBlobFileType> OnLazyLoadRequest = delegate { }; // Empty delegate. Thus we are sure that value is always != null because no one outside of the class can change it.
		private xDTO.BlobFileType _dto = null;

		public BlobFileType(ILoggingService log, IDataService<IWebApiDataServiceCM> dataService) : base(log, dataService)
		{
			_dto = new xDTO.BlobFileType();
			OnLazyLoadRequest += HandleLazyLoadRequest;
		}

		public BlobFileType(ILoggingService log, IDataService<IWebApiDataServiceCM> dataService, xDTO.BlobFileType dto) : this(log, dataService)
		{
			_dto = dto;
		}


		public virtual int BlobFileTypeId { get { return _dto.BlobFileTypeId; } }
		public virtual string CategoryType { get { return _dto.CategoryType; } }
		public virtual string CreatedBy { get { return _dto.CreatedBy; } }
		public virtual System.DateTime CreatedUtcDate { get { return _dto.CreatedUtcDate; } }
		public virtual int DataVersion { get { return _dto.DataVersion; } }
		public virtual string GeneralType { get { return _dto.GeneralType; } }
		public virtual bool IsDeleted { get { return _dto.IsDeleted; } }
		public virtual string ModifiedBy { get { return _dto.ModifiedBy; } }
		public virtual System.DateTime ModifiedUtcDate { get { return _dto.ModifiedUtcDate; } }
		public virtual string Name { get { return _dto.Name; } }
		public virtual int? ResizeFromBlobFileTypeId { get { return _dto.ResizeFromBlobFileTypeId; } }
		public virtual int? ResolutionX { get { return _dto.ResolutionX; } }
		public virtual int? ResolutionY { get { return _dto.ResolutionY; } }

		// Excluding 'BlobFileType' per configuration setting.
		// Excluding 'BlobFiles' per configuration setting.
		// Excluding 'BlobFileTypes' per configuration setting.




	}
}
