// <auto-generated> - Template:ModelsBackedByDto, Version:1.1, Id:f1539c0d-024f-4b1f-b346-132cdd9dd31f
using CodeGenHero.Logging;
using CodeGenHero.DataService;
using System;
using System.Collections.Generic;
using System.Linq;
using MSC.ConferenceMate.API.Client.Interface;
using MSC.ConferenceMate.Model.CM.Interface;
using xDTO = MSC.ConferenceMate.DTO.CM;

namespace MSC.ConferenceMate.Model.CM
{

	public class LoadRequestFeedbackInitiatorType : EventArgs
	{
		public LoadRequestFeedbackInitiatorType(string propertyNameRequestingLoad)
		{
			PropertyNameRequestingLoad = propertyNameRequestingLoad;
		}

		public string PropertyNameRequestingLoad { get; set; }
	}


	public partial class FeedbackInitiatorType : BaseModel<IWebApiDataServiceCM>, IFeedbackInitiatorType
	{
		public event EventHandler<LoadRequestFeedbackInitiatorType> OnLazyLoadRequest = delegate { }; // Empty delegate. Thus we are sure that value is always != null because no one outside of the class can change it.
		private xDTO.FeedbackInitiatorType _dto = null;

		public FeedbackInitiatorType(ILoggingService log, IDataService<IWebApiDataServiceCM> dataService) : base(log, dataService)
		{
			_dto = new xDTO.FeedbackInitiatorType();
			OnLazyLoadRequest += HandleLazyLoadRequest;
		}

		public FeedbackInitiatorType(ILoggingService log, IDataService<IWebApiDataServiceCM> dataService, xDTO.FeedbackInitiatorType dto) : this(log, dataService)
		{
			_dto = dto;
		}


		public virtual string Code { get { return _dto.Code; } }
		public virtual string CreatedBy { get { return _dto.CreatedBy; } }
		public virtual System.DateTime CreatedUtcDate { get { return _dto.CreatedUtcDate; } }
		public virtual int DataVersion { get { return _dto.DataVersion; } }
		public virtual int FeedbackInitiatorTypeId { get { return _dto.FeedbackInitiatorTypeId; } }
		public virtual bool IsDeleted { get { return _dto.IsDeleted; } }
		public virtual string ModifiedBy { get { return _dto.ModifiedBy; } }
		public virtual System.DateTime ModifiedUtcDate { get { return _dto.ModifiedUtcDate; } }

		// Excluding 'Feedbacks' per configuration setting.




	}
}
