// <auto-generated> - Template:ModelsBackedByDto, Version:1.1, Id:f1539c0d-024f-4b1f-b346-132cdd9dd31f
using CodeGenHero.Logging;
using CodeGenHero.DataService;
using System;
using System.Collections.Generic;
using System.Linq;
using MSC.ConferenceMate.API.Client.Interface;
using MSC.ConferenceMate.Model.CM.Interface;
using xDTO = MSC.ConferenceMate.DTO.CM;

namespace MSC.ConferenceMate.Model.CM
{

	public class LoadRequestLanguageType : EventArgs
	{
		public LoadRequestLanguageType(string propertyNameRequestingLoad)
		{
			PropertyNameRequestingLoad = propertyNameRequestingLoad;
		}

		public string PropertyNameRequestingLoad { get; set; }
	}


	public partial class LanguageType : BaseModel<IWebApiDataServiceCM>, ILanguageType
	{
		public event EventHandler<LoadRequestLanguageType> OnLazyLoadRequest = delegate { }; // Empty delegate. Thus we are sure that value is always != null because no one outside of the class can change it.
		private xDTO.LanguageType _dto = null;

		public LanguageType(ILoggingService log, IDataService<IWebApiDataServiceCM> dataService) : base(log, dataService)
		{
			_dto = new xDTO.LanguageType();
			OnLazyLoadRequest += HandleLazyLoadRequest;
		}

		public LanguageType(ILoggingService log, IDataService<IWebApiDataServiceCM> dataService, xDTO.LanguageType dto) : this(log, dataService)
		{
			_dto = dto;
		}


		public virtual string Code { get { return _dto.Code; } }
		public virtual string CreatedBy { get { return _dto.CreatedBy; } }
		public virtual System.DateTime CreatedUtcDate { get { return _dto.CreatedUtcDate; } }
		public virtual int DataVersion { get { return _dto.DataVersion; } }
		public virtual int DisplayPriority { get { return _dto.DisplayPriority; } }
		public virtual string DisplayText { get { return _dto.DisplayText; } }
		public virtual bool IsDeleted { get { return _dto.IsDeleted; } }
		public virtual int? LanguageCultureIdentifier { get { return _dto.LanguageCultureIdentifier; } }
		public virtual int LanguageTypeId { get { return _dto.LanguageTypeId; } }
		public virtual string ModifiedBy { get { return _dto.ModifiedBy; } }
		public virtual System.DateTime ModifiedUtcDate { get { return _dto.ModifiedUtcDate; } }
		public virtual string NativeName { get { return _dto.NativeName; } }
		public virtual string ThreeLetterIsoLanguageName { get { return _dto.ThreeLetterIsoLanguageName; } }
		public virtual string TwoLetterIsoLanguageName { get { return _dto.TwoLetterIsoLanguageName; } }

		// Excluding 'LookupLists' per configuration setting.
		private List<IUserProfile> _userProfiles = null; // Reverse Navigation


		public virtual List<IUserProfile> UserProfiles
		{
			get
			{
				if (_userProfiles == null && _dto != null)
				{	// The core DTO object is loaded, but this property is not loaded.
					if (_dto.UserProfiles != null)
					{	// The core DTO object has data for this property, load it into the model.
						_userProfiles = new List<IUserProfile>();
						foreach (var dtoItem in _dto.UserProfiles)
						{
							_userProfiles.Add(new UserProfile(Log, DataService, dtoItem));
						}
					}
					else
					{	// Trigger the load data request - The core DTO object is loaded and does not have data for this property.
						OnLazyLoadRequest(this, new LoadRequestLanguageType(nameof(UserProfiles)));
					}
				}

				return _userProfiles;
			}
		}



	}
}
