// <auto-generated> - Template:ModelsBackedByDtoInterface, Version:1.1, Id:4d03f2c7-de27-4aae-a267-cad747c9606a
using System;
using System.Collections.Generic;

namespace MSC.ConferenceMate.Model.CM.Interface
{
	public partial interface IBlobFileType
	{
		int BlobFileTypeId { get; }
		string CategoryType { get; }
		string CreatedBy { get; }
		System.DateTime CreatedUtcDate { get; }
		int DataVersion { get; }
		string GeneralType { get; }
		bool IsDeleted { get; }
		string ModifiedBy { get; }
		System.DateTime ModifiedUtcDate { get; }
		string Name { get; }
		int? ResizeFromBlobFileTypeId { get; }
		int? ResolutionX { get; }
		int? ResolutionY { get; }

		// Excluding 'BlobFileType' per configuration setting.
		// Excluding 'BlobFile' per configuration setting.
		// Excluding 'BlobFileType' per configuration setting.


	}
}
