// <auto-generated> - Template:ModelsBackedByDtoInterface, Version:1.1, Id:4d03f2c7-de27-4aae-a267-cad747c9606a
using System;
using System.Collections.Generic;

namespace MSC.ConferenceMate.Model.CM.Interface
{
	public partial interface IFeaturedEvent
	{
		string CreatedBy { get; }
		System.DateTime CreatedUtcDate { get; }
		int DataVersion { get; }
		string Description { get; }
		System.DateTime? EndTime { get; }
		int FeaturedEventId { get; }
		bool IsAllDay { get; }
		bool IsDeleted { get; }
		string Location { get; }
		string ModifiedBy { get; }
		System.DateTime ModifiedUtcDate { get; }
		string ShortTitle { get; }
		System.DateTime? StartTime { get; }
		string Title { get; }

		List<IFeedback> Feedbacks { get; }
		List<ISponsorFeaturedEvent> SponsorFeaturedEvents { get; }


	}
}
