// <auto-generated> - Template:ModelsBackedByDtoInterface, Version:1.1, Id:4d03f2c7-de27-4aae-a267-cad747c9606a
using System;
using System.Collections.Generic;

namespace MSC.ConferenceMate.Model.CM.Interface
{
	public partial interface ILanguageType
	{
		string Code { get; }
		string CreatedBy { get; }
		System.DateTime CreatedUtcDate { get; }
		int DataVersion { get; }
		int DisplayPriority { get; }
		string DisplayText { get; }
		bool IsDeleted { get; }
		int? LanguageCultureIdentifier { get; }
		int LanguageTypeId { get; }
		string ModifiedBy { get; }
		System.DateTime ModifiedUtcDate { get; }
		string NativeName { get; }
		string ThreeLetterIsoLanguageName { get; }
		string TwoLetterIsoLanguageName { get; }

		// Excluding 'LookupList' per configuration setting.
		List<IUserProfile> UserProfiles { get; }


	}
}
