// <auto-generated> - Template:ModelsBackedByDtoInterface, Version:1.1, Id:4d03f2c7-de27-4aae-a267-cad747c9606a
using System;
using System.Collections.Generic;

namespace MSC.ConferenceMate.Model.CM.Interface
{
	public partial interface ILog
	{
		string ClientIpAddress { get; }
		System.DateTime Date { get; }
		string Exception { get; }
		long? ExecutionTimeInMilliseconds { get; }
		string HttpResponseStatusCode { get; }
		int Id { get; }
		string Level { get; }
		string Logger { get; }
		System.Guid? LogGuid { get; }
		int? LogMessageTypeId { get; }
		string Message { get; }
		string MethodName { get; }
		string Thread { get; }
		string Url { get; }
		string UserName { get; }



	}
}
