// <auto-generated> - Template:ModelsBackedByDtoInterface, Version:1.1, Id:4d03f2c7-de27-4aae-a267-cad747c9606a
using System;
using System.Collections.Generic;

namespace MSC.ConferenceMate.Model.CM.Interface
{
	public partial interface ISponsor
	{
		string BoothLocation { get; }
		string CreatedBy { get; }
		System.DateTime CreatedUtcDate { get; }
		int DataVersion { get; }
		string Description { get; }
		string ImageUrl { get; }
		bool IsDeleted { get; }
		string ModifiedBy { get; }
		System.DateTime ModifiedUtcDate { get; }
		int Rank { get; }
		string ShortTitle { get; }
		int SponsorId { get; }
		int SponsorTypeId { get; }
		string Title { get; }
		string TwitterUrl { get; }
		string WebsiteUrl { get; }

		ISponsorType SponsorType { get; }
		List<ISponsorFeaturedEvent> SponsorFeaturedEvents { get; }


	}
}
