// <auto-generated> - Template:RepositoryInterfaceCrud, Version:1.1, Id:387dfdc5-b9f2-4ab4-accb-00a22cdd916c
using CodeGenHero.Repository;
using MSC.ConferenceMate.Repository.Entities.CM;
using System.Linq;

namespace MSC.ConferenceMate.Repository.Interface
{
	public interface ICMRepositoryCrud : 
		ICRUDOperation<Announcement>,
		ICRUDOperation<BlobFile>,
		ICRUDOperation<BlobFileType>,
		ICRUDOperation<FeaturedEvent>,
		ICRUDOperation<Feedback>,
		ICRUDOperation<FeedbackInitiatorType>,
		ICRUDOperation<FeedbackType>,
		ICRUDOperation<GenderType>,
		ICRUDOperation<LanguageType>,
		ICRUDOperation<Log>,
		ICRUDOperation<LogType>,
		ICRUDOperation<LookupList>,
		ICRUDOperation<Room>,
		ICRUDOperation<Session>,
		ICRUDOperation<SessionCategoryType>,
		ICRUDOperation<SessionLike>,
		ICRUDOperation<SessionSessionCategoryType>,
		ICRUDOperation<SessionSpeaker>,
		ICRUDOperation<Sponsor>,
		ICRUDOperation<SponsorFeaturedEvent>,
		ICRUDOperation<SponsorType>,
		ICRUDOperation<UserProfile>
	{

		#region GetQueryable

		IQueryable<Announcement> GetQueryable_Announcement();
		IQueryable<BlobFile> GetQueryable_BlobFile();
		IQueryable<BlobFileType> GetQueryable_BlobFileType();
		IQueryable<FeaturedEvent> GetQueryable_FeaturedEvent();
		IQueryable<Feedback> GetQueryable_Feedback();
		IQueryable<FeedbackInitiatorType> GetQueryable_FeedbackInitiatorType();
		IQueryable<FeedbackType> GetQueryable_FeedbackType();
		IQueryable<GenderType> GetQueryable_GenderType();
		IQueryable<LanguageType> GetQueryable_LanguageType();
		IQueryable<Log> GetQueryable_Log();
		IQueryable<LogType> GetQueryable_LogType();
		IQueryable<LookupList> GetQueryable_LookupList();
		IQueryable<Room> GetQueryable_Room();
		IQueryable<Session> GetQueryable_Session();
		IQueryable<SessionCategoryType> GetQueryable_SessionCategoryType();
		IQueryable<SessionLike> GetQueryable_SessionLike();
		IQueryable<SessionSessionCategoryType> GetQueryable_SessionSessionCategoryType();
		IQueryable<SessionSpeaker> GetQueryable_SessionSpeaker();
		IQueryable<Sponsor> GetQueryable_Sponsor();
		IQueryable<SponsorFeaturedEvent> GetQueryable_SponsorFeaturedEvent();
		IQueryable<SponsorType> GetQueryable_SponsorType();
		IQueryable<UserProfile> GetQueryable_UserProfile();

		#endregion

	}
}
