// <auto-generated> - Template:Repository, Version:1.1, Id:c765a56c-163b-4d2a-863d-3a0a30bbcb15
using MSC.ConferenceMate.Repository.Entities.CM;
using MSC.ConferenceMate.Repository.Interface;
using System;
using System.Data.Entity;
using System.Linq;

namespace MSC.ConferenceMate.Repository
{
	public partial class CMRepository : CMRepositoryBase, ICMRepository
	{
		private ICMDataContext _ctx;

		public CMRepository(ICMDataContext ctx) : base(ctx)
		{
			_ctx = ctx;

			// Disable lazy loading - if not, related properties are auto-loaded when
			// they are accessed for the first time, which means they'll be included when
			// we serialize (b/c the serialization process accesses those properties).

			// We don't want that, so we turn it off.  We want to eagerly load them (using Include) manually.

			ctx.Configuration.LazyLoadingEnabled = false;

			if (System.Diagnostics.Debugger.IsAttached)
			{   // Write EF queries to the output console.
				ctx.Database.Log = x => System.Diagnostics.Debug.WriteLine(x);
			}
		}

		public ICMDataContext CMDataContext { get { return _ctx; } }

	}
}
