// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;

namespace MSC.CM.Xam.ModelData.CM
{
	public static class DemoAnnouncement
	{
		public static int SampleAnnouncementId0000 = 1952125025;
		public static int SampleAnnouncementId0100 = 1030480622;

		public static Announcement SampleAnnouncement00
		{
			get
			{
				return new Announcement()
				{
					AnnouncementId = SampleAnnouncementId0000,
					Title = "SampleTitle",
					ShortTitle = "SampleShortTitle",
					Description = "SampleDescription",
					StartTime = DateTime.Now,
					EndTime = DateTime.Now,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}
		public static Announcement SampleAnnouncement01
		{
			get
			{
				return new Announcement()
				{
					AnnouncementId = SampleAnnouncementId0100,
					Title = "SampleTitle",
					ShortTitle = "SampleShortTitle",
					Description = "SampleDescription",
					StartTime = DateTime.Now,
					EndTime = DateTime.Now,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}

	}
}
