// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;

namespace MSC.CM.Xam.ModelData.CM
{
	public static class DemoFeaturedEvent
	{
		public static int SampleFeaturedEventId0000 = 360146547;
		public static int SampleFeaturedEventId0100 = 480728670;

		public static FeaturedEvent SampleFeaturedEvent00
		{
			get
			{
				return new FeaturedEvent()
				{
					FeaturedEventId = SampleFeaturedEventId0000,
					Title = "SampleTitle",
					ShortTitle = "SampleShortTitle",
					Description = "SampleDescription",
					Location = "SampleLocation",
					StartTime = DateTime.Now,
					EndTime = DateTime.Now,
					IsAllDay = false,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}
		public static FeaturedEvent SampleFeaturedEvent01
		{
			get
			{
				return new FeaturedEvent()
				{
					FeaturedEventId = SampleFeaturedEventId0100,
					Title = "SampleTitle",
					ShortTitle = "SampleShortTitle",
					Description = "SampleDescription",
					Location = "SampleLocation",
					StartTime = DateTime.Now,
					EndTime = DateTime.Now,
					IsAllDay = false,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}

	}
}
