// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;

namespace MSC.CM.Xam.ModelData.CM
{
	public static class DemoFeedbackInitiatorType
	{
		public static int SampleFeedbackInitiatorTypeId0000 = 360146547;
		public static int SampleFeedbackInitiatorTypeId0100 = 480728670;

		public static FeedbackInitiatorType SampleFeedbackInitiatorType00
		{
			get
			{
				return new FeedbackInitiatorType()
				{
					FeedbackInitiatorTypeId = SampleFeedbackInitiatorTypeId0000,
					Code = "SampleCode",
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}
		public static FeedbackInitiatorType SampleFeedbackInitiatorType01
		{
			get
			{
				return new FeedbackInitiatorType()
				{
					FeedbackInitiatorTypeId = SampleFeedbackInitiatorTypeId0100,
					Code = "SampleCode",
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}

	}
}
