// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;

namespace MSC.CM.Xam.ModelData.CM
{
	public static class DemoFeedbackType
	{
		public static int SampleFeedbackTypeId0000 = 360146547;
		public static int SampleFeedbackTypeId0100 = 480728670;

		public static FeedbackType SampleFeedbackType00
		{
			get
			{
				return new FeedbackType()
				{
					FeedbackTypeId = SampleFeedbackTypeId0000,
					Code = "SampleCode",
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}
		public static FeedbackType SampleFeedbackType01
		{
			get
			{
				return new FeedbackType()
				{
					FeedbackTypeId = SampleFeedbackTypeId0100,
					Code = "SampleCode",
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}

	}
}
