// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;

namespace MSC.CM.Xam.ModelData.CM
{
	public static class DemoLanguageType
	{
		public static int SampleLanguageTypeId0000 = 1851998887;
		public static int SampleLanguageTypeId0100 = 1372120977;

		public static LanguageType SampleLanguageType00
		{
			get
			{
				return new LanguageType()
				{
					LanguageTypeId = SampleLanguageTypeId0000,
					Code = "SampleCode",
					DisplayText = "SampleDisplayText",
					DisplayPriority = 0,
					NativeName = "SampleNativeName",
					ThreeLetterIsoLanguageName = "SampleThreeLetterIsoLanguageName",
					TwoLetterIsoLanguageName = "SampleTwoLetterIsoLanguageName",
					LanguageCultureIdentifier = 0,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}
		public static LanguageType SampleLanguageType01
		{
			get
			{
				return new LanguageType()
				{
					LanguageTypeId = SampleLanguageTypeId0100,
					Code = "SampleCode",
					DisplayText = "SampleDisplayText",
					DisplayPriority = 0,
					NativeName = "SampleNativeName",
					ThreeLetterIsoLanguageName = "SampleThreeLetterIsoLanguageName",
					TwoLetterIsoLanguageName = "SampleTwoLetterIsoLanguageName",
					LanguageCultureIdentifier = 0,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}

	}
}
