// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;

namespace MSC.CM.Xam.ModelData.CM
{
	public static class DemoLog
	{
		public static int SampleLogId0000 = 1851998887;
		public static int SampleLogId0100 = 1372120977;

		public static Log SampleLog00
		{
			get
			{
				return new Log()
				{
					Id = SampleLogId0000,
					Date = DateTime.Now,
					Thread = "SampleThread",
					Level = "SampleLevel",
					Logger = "SampleLogger",
					Message = "SampleMessage",
					Exception = "SampleException",
					LogMessageTypeId = 0,
					MethodName = "SampleMethodName",
					UserName = "SampleUserName",
					ClientIpAddress = "SampleClientIpAddress",
					LogGuid = Guid.Parse("2894bae6-8079-4580-a250-8136f4d26613"),
					ExecutionTimeInMilliseconds = 0,
					HttpResponseStatusCode = "SampleHttpResponseStatusCode",
					Url = "SampleUrl",
				};
			}
		}
		public static Log SampleLog01
		{
			get
			{
				return new Log()
				{
					Id = SampleLogId0100,
					Date = DateTime.Now,
					Thread = "SampleThread",
					Level = "SampleLevel",
					Logger = "SampleLogger",
					Message = "SampleMessage",
					Exception = "SampleException",
					LogMessageTypeId = 0,
					MethodName = "SampleMethodName",
					UserName = "SampleUserName",
					ClientIpAddress = "SampleClientIpAddress",
					LogGuid = Guid.Parse("8a894b8e-1d8c-47cf-a69d-00d00b966bdf"),
					ExecutionTimeInMilliseconds = 0,
					HttpResponseStatusCode = "SampleHttpResponseStatusCode",
					Url = "SampleUrl",
				};
			}
		}

	}
}
