// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;

namespace MSC.CM.Xam.ModelData.CM
{
	public static class DemoSessionSpeaker
	{
		public static int SampleSessionSpeakerId0000 = DemoSession.SampleSessionId0000;
		public static int SampleSessionSpeakerUserProfileId0001 = DemoUserProfile.SampleUserProfileId0000;
		public static int SampleSessionSpeakerId0100 = DemoSession.SampleSessionId0100;
		public static int SampleSessionSpeakerUserProfileId0101 = DemoUserProfile.SampleUserProfileId0100;

		public static SessionSpeaker SampleSessionSpeaker00
		{
			get
			{
				return new SessionSpeaker()
				{
					SessionId = SampleSessionSpeakerId0000,
					UserProfileId = SampleSessionSpeakerUserProfileId0001,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
                    SessionIdUserProfileId = $"{SampleSessionSpeakerId0000}{SampleSessionSpeakerUserProfileId0001}"
				};
			}
		}
		public static SessionSpeaker SampleSessionSpeaker01
		{
			get
			{
				return new SessionSpeaker()
				{
					SessionId = SampleSessionSpeakerId0100,
					UserProfileId = SampleSessionSpeakerUserProfileId0101,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
                    SessionIdUserProfileId = $"{SampleSessionSpeakerId0100}{SampleSessionSpeakerUserProfileId0101}"
                };
			}
		}

	}
}
