// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;

namespace MSC.CM.Xam.ModelData.CM
{
	public static class DemoSessionSessionCategoryType
	{
		public static int SampleSessionSessionCategoryTypeId0000 = DemoSession.SampleSessionId0000;
		public static int SampleSessionSessionCategoryTypeId0001 = DemoSessionCategoryType.SampleSessionCategoryTypeId0000;
		public static int SampleSessionSessionCategoryTypeId0100 = DemoSession.SampleSessionId0100;
		public static int SampleSessionSessionCategoryTypeId0101 = DemoSessionCategoryType.SampleSessionCategoryTypeId0100;

		public static SessionSessionCategoryType SampleSessionSessionCategoryType00
		{
			get
			{
				return new SessionSessionCategoryType()
				{
					SessionId = SampleSessionSessionCategoryTypeId0000,
					SessionCategoryTypeId = SampleSessionSessionCategoryTypeId0001,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}
		public static SessionSessionCategoryType SampleSessionSessionCategoryType01
		{
			get
			{
				return new SessionSessionCategoryType()
				{
					SessionId = SampleSessionSessionCategoryTypeId0100,
					SessionCategoryTypeId = SampleSessionSessionCategoryTypeId0101,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}

	}
}
