// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;

namespace MSC.CM.Xam.ModelData.CM
{
	public static class DemoSponsorType
	{
		public static int SampleSponsorTypeId0000 = 566255897;
		public static int SampleSponsorTypeId0100 = 1805148081;

		public static SponsorType SampleSponsorType00
		{
			get
			{
				return new SponsorType()
				{
					SponsorTypeId = SampleSponsorTypeId0000,
					Code = "SampleCode",
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}
		public static SponsorType SampleSponsorType01
		{
			get
			{
				return new SponsorType()
				{
					SponsorTypeId = SampleSponsorTypeId0100,
					Code = "SampleCode",
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}

	}
}
