// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;

namespace MSC.CM.Xam.ModelData.CM
{
	public static class DemoSponsor
	{
		public static int SampleSponsorId0000 = 566255897;
		public static int SampleSponsorId0100 = 1805148081;

		public static Sponsor SampleSponsor00
		{
			get
			{
				return new Sponsor()
				{
					SponsorId = SampleSponsorId0000,
					SponsorTypeId = 0,
					Title = "SampleTitle",
					ShortTitle = "SampleShortTitle",
					Description = "SampleDescription",
					ImageUrl = "SampleImageUrl",
					WebsiteUrl = "SampleWebsiteUrl",
					TwitterUrl = "SampleTwitterUrl",
					BoothLocation = "SampleBoothLocation",
					Rank = 0,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}
		public static Sponsor SampleSponsor01
		{
			get
			{
				return new Sponsor()
				{
					SponsorId = SampleSponsorId0100,
					SponsorTypeId = 0,
					Title = "SampleTitle",
					ShortTitle = "SampleShortTitle",
					Description = "SampleDescription",
					ImageUrl = "SampleImageUrl",
					WebsiteUrl = "SampleWebsiteUrl",
					TwitterUrl = "SampleTwitterUrl",
					BoothLocation = "SampleBoothLocation",
					Rank = 0,
					DataVersion = 0,
					CreatedUtcDate = DateTime.Now,
					CreatedBy = "SampleCreatedBy",
					ModifiedUtcDate = DateTime.Now,
					ModifiedBy = "SampleModifiedBy",
					IsDeleted = false,
				};
			}
		}

	}
}
